name: nextcloud-desktop-client
version: '3.5.3'
base: core20
summary: Nextcloud Desktop Client
description: |
  Use the desktop clients to keep your files synchronized between your Nextcloud server and your desktop. Select one or more directories on your local machine and always have access to your latest files wherever you are. 

  https://nextcloud.com/install/#install-clients

  **Disclaimer:**

  This is not an official version of the Nextcloud Desktop Client! It is build from the release sources but depends an other runtime libraries (Ubuntu Core 20, etc.) than the official version.
  All product and company names are trademarks™ or registered® trademarks of their respective holders. Use of them does not imply any affiliation with or endorsement by them. 


architectures:
  - build-on: [amd64, arm64]
    run-on: [amd64, arm64]


grade: stable
confinement: strict

compression: lzo

icon: snap/gui/nextcloud.png

assumes:
  - command-chain

plugs:
  gnome-3-38-2004:
    default-provider: gnome-3-38-2004
    interface: content
    target: $SNAP/gnome-platform
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes
  
apps:
  nextcloudcmd:
    adapter: full
    command: usr/bin/nextcloudcmd
    plugs:
      - home
      - network
      - network-bind
    
  nextcloud:
    adapter: full
    extensions: [gnome-3-38]
    command-chain:
      - bin/desktop-launch
      - bin/homeishome-launch        
    command: usr/bin/nextcloud
    environment:
      NO_AT_BRIDGE: 1
      DISABLE_WAYLAND: 1
      QT_QPA_PLATFORMTHEME: gtk3
    autostart: com.nextcloud.desktopclient.nextcloud.desktop

    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - network-manager-observe
      - opengl
      - password-manager-service
      - unity7
      - wayland
      - removable-media
    
build-packages:
  - build-essential
  - cmake
  - dpkg-dev
  - libcloudproviders-dev
  - libqt5svg5-dev
  - libqt5websockets5-dev
  - librsvg2-bin
  - libsqlite3-dev
  - libssl-dev
  - qt5keychain-dev
  - qtbase5-dev
  - qtbase5-private-dev
  - qtquickcontrols2-5-dev
  - qttools5-dev
  - qtwebengine5-dev
  - wget
  - zlib1g-dev


package-repositories:
  - type: apt
    components: [main]
    suites: [focal]
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://archive.neon.kde.org/user


layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/share/qt5/resources:
    bind: $SNAP/usr/share/qt5/resources
  /usr/share/qt5/translations/qtwebengine_locales:
    bind: $SNAP/usr/share/qt5/translations/qtwebengine_locales
  /usr/share/nextcloud:
    bind: $SNAP/usr/share/nextcloud
  /etc/Nextcloud:
    bind: $SNAP/etc/Nextcloud

parts:
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch     

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    stage-packages:
      - adwaita-icon-theme
      - dmz-cursor-theme
      - fcitx-frontend-qt5
      - gnome-themes-standard
      - libgdk-pixbuf2.0-0
      - libgtk2.0-0
      - libqt5gui5
      - libqt5svg5
      - libxkbcommon0
      - light-themes
      - locales-all
      - qt5-gtk-platformtheme
      - shared-mime-info
      - ttf-ubuntu-font-family
      - xdg-user-dirs


  nextcloud-desktop-client:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RELEASE
      - -DCMAKE_INSTALL_PREFIX=/usr/
      - -DCMAKE_PREFIX_PATH="${SNAPCRAFT_STAGE}/usr"
      - -DBUILD_TESTING=OFF
      - -DBUILD_UPDATER=OFF
      - -DBUILD_SHELL_INTEGRATION=OFF
      - -DBUILD_SHELL_INTEGRATION_ICONS=OFF
      - -DBUILD_SHELL_INTEGRATION_DOLPHIN=OFF
      - -DBUILD_SHELL_INTEGRATION_NAUTILUS=OFF
      - -DWITH_CRASHREPORTER=OFF
    source: https://github.com/nextcloud/desktop/archive/refs/tags/v3.5.3.tar.gz
    source-type: tar
    override-pull: |
      snapcraftctl pull
      patch -p1 < "${SNAPCRAFT_PROJECT_DIR}/patches/disable_debug_logging.diff"
    stage:
      - -usr/share/caja-python
      - -usr/share/nautilus-python
      - -usr/share/nemo-python
      - -usr/share/applications
      - -usr/include/
    stage-packages:
      - libcloudproviders0
      - libqt5keychain1
      - libqt5quickcontrols2-5
      - libqt5quicktemplates2-5
      - libqt5webengine-data
      - libqt5webengine5
      - libqt5webenginecore5
      - libqt5webenginewidgets5
      - libqt5websockets5
      - qml-module-qt-labs-platform
      - qml-module-qtgraphicaleffects
      - qml-module-qtmultimedia
      - qml-module-qtqml
      - qml-module-qtqml-models2
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qt5-image-formats-plugins
      - qt5-qmltooling-plugins
      - qttranslations5-l10n
      - qtwayland5
    after:
      - desktop-qt5
    